coverage:
  precision: 2
  round: down
  range: "35...100"
  status:
    project:
      default:
        informational: true
    patch: off
fixes:
  - "ws_rmf/src/rmf_core/::"
comment:
  layout: "reach, diff, flags, files"
  behavior: new
  require_changes: false
ignore:
  - "ws_rmf/build"
