name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: docker://ros:foxy-ros-base-focal
      
    steps:
    - name: deps
      run: |
        sudo apt update
        sudo apt install -y g++-8
    - name: setup
      run: |
        mkdir -p ws_rmf/src        
    - name: checkout
      uses: actions/checkout@v2
      with:
        path: ws_rmf/src/rmf_core
    - name: ros-deps
      run: |
        cd ws_rmf
        rosdep update
        rosdep install --from-paths src --ignore-src --rosdistro foxy -yr
    - name: build
      shell: bash
      run: |
        cd ws_rmf
        source /opt/ros/foxy/setup.bash
        colcon build --cmake-args -DCMAKE_BUILD_TYPE=RELEASE
    - name: build_with_codecov
      shell: bash
      run: |
        apt update
        apt install lcov
        pip3 install lcov
        cd ws_rmf
        colcon build --symlink-install --cmake-args -DCMAKE_CXX_FLAGS='-fprofile-arcs -ftest-coverage' -DCMAKE_C_FLAGS='-fprofile-arcs -ftest-coverage'
        colcon lcov-result --initial
        colcon test
        colcon lcov-result
        #upload lcov/index.html to codecov.io
